set nocompatible
set t_Co=256

filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle 'gmarik/Vundle.vim'

Bundle 'editorconfig/editorconfig-vim'
Bundle 'goatslacker/mango.vim'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'Lokaltog/vim-powerline'
Bundle 'scrooloose/syntastic'
Bundle 'bling/vim-airline'
Bundle 'docunext/closetag.vim'
Bundle 'othree/html5.vim'
Bundle 'othree/javascript-libraries-syntax.vim'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'mustache/vim-mustache-handlebars'
Bundle 'hail2u/vim-css3-syntax'
Bundle 'benmills/vimux'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-sensible'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-fugitive'
Bundle 'jiangmiao/simple-javascript-indenter'
Bundle 'maksimr/vim-jsbeautify'
Bundle 'einars/js-beautify'
Bundle 'claco/jasmine.vim'
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'garbas/vim-snipmate'
Bundle 'groenewege/vim-less'

call vundle#end()
filetype plugin on

set number
set laststatus=2
set hlsearch
set incsearch
set nobackup
set ruler
set visualbell t_vb=
set backspace=2
set textwidth=80
set colorcolumn=+1

set list listchars=tab:▸\ ,eol:¬

set autoindent
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab
set pastetoggle=<F2>
set exrc
set secure
set autoread

set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

set cpoptions+=$
set backupcopy=yes

let g:syntastic_check_on_open=1
let g:airline_theme='luna'
let g:airline_powerline_fonts=1

set background=dark
syntax on
colorscheme hemisu

let g:badwolf_css_props_highlight=1
let g:badwolf_darkgutter=1

let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

hi Normal ctermbg=NONE

map <C-n> :NERDTreeToggle<cr>
let NERDTreeShowHidden=1

map <leader>h :nohlsearch<cr>
map <leader>l :set list!<cr>

fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline

autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

map <c-f> :call JsBeautify()<cr>
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>

map rp :VimuxPromptCommand
map rl :VimuxRunCommand
map ri :VimuxInspectRunner
map rx :VimuxClosePanes
map rs :VimuxInterruptRunner

:ca WQ wq
:ca Wq wq
:ca W w
:ca Q q
