set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'tpope/vim-sensible'
Bundle 'kien/ctrlp.vim'
Bundle 'Lokaltogvim-powerline'
Bundle 'scrooloose/nerdtree'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'pangloss/vim-javascript'
Bundle 'scrooloose/syntastic'
Bundle 'bling/vim-airline'
Bundle 'altercation/vim-colors-solarized'
Bundle 'docunext/closetag.vim'
Bundle 'Raimondi/delimitMate'
Bundle 'mustache/vim-mustache-handlebars'

Bundle 'hail2u/vim-css3-syntax'
Bundle 'othree/html5-syntax.vim'
Bundle 'tpope/vim-markdown'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'othree/javascript-libraries-syntax.vim'
Bundle 'jiangmiao/simple-javascript-indenter'
Bundle 'tpope/vim-haml'
Bundle 'maksimr/vim-jsbeautify'
Bundle 'einars/js-beautify'

set shiftwidth=2
set number
set laststatus=2
set hlsearch
set incsearch
set nobackup
set ruler
set textwidth=80
set visualbell t_vb=
set t_Co=16

set listchars=tab:▸\ ,eol:¬

set autoindent
set noexpandtab
set tabstop=4
set shiftwidth=4
set pastetoggle=<F2>
set exrc
set secure

set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

let g:syntastic_check_on_open=1
let g:airline_theme='luna'
let g:airline_powerline_fonts=1
let g:solarized_termcolors=16

filetype plugin indent on
set autoindent

syntax on
colorscheme solarized
set background=dark
set autoread

set cursorline
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline

map <C-n> :NERDTreeToggle<cr>
map <leader>h :nohlsearch<cr>
map <leader>l :set list!<cr>

fun! <SID>StripTrailingWhitespaces()
	let l = line(".")
	let c = col(".")
	%s/\s\+$//e
	call cursor(l, c)
endfun

autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

map <c-f> :call JsBeautify()<cr>
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
